---
- name: Deploy app
  hosts: localhost
  connection: local
  vars:
    default_container_name: docker-demo
    default_container_image: docker.io/elasticobservability/demo-fosdem:0.0.1

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
        ports:
          - "28080:8080"
