---
- name: Deploy demo app
  hosts: localhost
  connection: local
  vars:
    default_container_name: anti-fraud-01
    default_container_image: docker.io/v1v1v/anti-fraud:0.0.1-SNAPSHOT
    port_container: 28080

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default container 01
      docker_container:
        name: "anti-fraud-01"
        image: "{{ default_container_image }}"
        state: started
        recreate: yes
        ports:
          - "28080:8080"
        networks:
          - name: infra_default

    - name: Create default container 02
      docker_container:
        name: "anti-fraud-02"
        image: "{{ default_container_image }}"
        state: started
        recreate: yes
        ports:
          - "28081:8080"
        networks:
          - name: infra_default
