---
- name: Deploy app
  hosts: localhost
  connection: local
  vars:
    default_container_name: antifraud-01
    default_container_image: docker.io/v1v1v/anti-fraud
    version: 0.0.1-SNAPSHOT
    port_container: 28080

  tasks:
    - name: Log into DockerHub
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
        registry_url: https://index.docker.io/v1/

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}:{{ version }}"
        source: pull

    - name: Spin up antifraud service
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}:{{ version }}"
        state: started
        recreate: yes
        ports:
          - "{{ port_container }}:8080"
        networks:
          - name: infra_default
        env:
          OTEL_SERVICE_NAME: "{{ default_container_name }}"
          ELASTIC_APM_SERVICE_VERSION: "Canary Deployment {{ version }}"
          ELASTIC_APM_ENVIRONMENT: 'production'
          ELASTIC_APM_TRANSACTION_SAMPLE_RATE: "1"

    - name: Healtcheck
      uri:
        url: "http://antifraud-01.example.com:28080/healthcheck"
      retries: 6
      delay: 3
      register: _result
      until: _result.status == 200
      ignore_errors: yes
